- README.md
This is a common section included in the README files for other projects that I maintain. I meant to include it here, but failed to do so when copy/pasting the initial content from another project.
> Add missing Project Home section

- CHANGELOG.md
This comes from rushing the release in order to make a deployment within a maintenance window (using a fixed version).
> Fix release date for v0.1.0

- doc.go
The "bullet points" were wrapping onto one line instead
of being separated into separate lines as a normal/supported
bulleted list would be. This commit adds an extra newline to
help force the items apart.
> Attempt to fix GoDoc formatting

- cmd/check_cert/main.go
- cmd/lscert/main.go
The prior check failed to take into the account the forced case-folding and whitespace-stripping applied to the first SANs entry value provided by the user.
fixes GH-17
> Apply intended SKIPSANSCHECK keyword validation

- .github/workflows/dependabot.yml
- go.mod files, ALL packages
- Daily at 2 am CT
- Assignee to me, label as "dependencies"
- Add `go.mod` prefix to associated PR commits
- Target `master` branch
- fixes GH-21
-  atc0005/todo#20
> Enable Dependabot version updates

- internal/certs/certs.go
There may be other cases, but this commit corrects two doc
comments containing stuttering func names.
Backstory:
These cases were some that I missed after enabling VSCode's
"replace" setting for the for `editor.suggest.insertMode`
option. While I tried to catch each incomplete replacement,
these two (and likely other) cases slipped past my notice.
Unfortunately, I've found that this setting can be buggy
at times which results in replacement text being appended
instead of overwriting the existing content, leading to
cases like these.
> Fix func doc comments stutter

- internal/certs/certs.go
Caught this while auditing date comparisons for GH-32.
The net effect appears to be a NOOP in terms of output changes, but should hopefully prevent surprises if the String() method call changes in the future.
> Replace debug String() call with explicit format

- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
Create a shared const within our internal certs package and reference it everywhere we previously used a
hard-coded date layout.
refs GH-34
> Use consistent & explicit validity date formatting

- .gitignore
Match on base repo path, not *anywhere* in the repo path
> Update .gitignore patterns for plugin name

- README.md
- cmd/check_cert/checkresults.go
- cmd/check_cert/config.go
- cmd/check_cert/main.go
- cmd/lscert/config.go
- cmd/lscert/main.go
- internal/certs/certs.go
Better convey what thresholds were used to determine the current
state results
- README
- Remove reference to setting values in a config file (not yet
implemented)
- Add additional coverage for threshold logic
- how it differs from the official `check_http` plugin
- UTC values (previously local time)
- emphasize that rounding is *not* used
- Change flag descriptions for threshold values in an attempt to
better explain the intent (coupled with the extra section for
threshold calculations, this should hopefully be clearer)
- `lscert`
- Fix struct field doc comment (referred to wrong field name)
- Explicitly set UTC location for `now` variables
- Add new output block to list WarningThreshold and
CriticalThreshold formatted strings
- expiration date thresholds in number of days
- expiration …
> Enhance expiration threshold coverage

- cmd/check_cert/main.go
- cmd/lscert/main.go
Fallback to first DNSName slice entry if Subject.CommonName
is not available from the certificate.
The assumption here is that *something* will be available in
the SANs list if the CommonName is empty. Further work may
be needed to guard against both fields being empty.
fixes GH-20
> Server name: Use CN if set, otherwise first SANs

- cmd/check_cert/main.go
- cmd/lscert/main.go
- go.mod
- go.sum
- internal/certs/certs.go
- vendor/github.com/atc0005/go-nagios/.golangci.yml
- vendor/github.com/atc0005/go-nagios/CHANGELOG.md
- vendor/github.com/atc0005/go-nagios/Makefile
- vendor/github.com/atc0005/go-nagios/README.md
- vendor/github.com/atc0005/go-nagios/main.go
- vendor/modules.txt
- shared
- Update to `atc0005/go-nagios@v0.3.0`
- replace hard-coded status strings with const references
- Create new `ChainStatus` type to encompass the shared cert
details computed throughout both `check_cert` and `lscert`
applications
- Update NextToExpire func to support including or excluding
expired certificates depending on the use case
- Add ChainSummary func to handle generating a ChainStatus value
for use throughout the application in place of one-off values
- Limit connection error scope
- `lscert`
- Tweak nextToExpire and statusOverview details to (hopefully) read
better at a quick glance
- Fix invalid cert count check
- `check_cert`
- rework one-line summary to provide feature parity with check_http
plugin, but with custom details specific to this plugin
- cert chain …
> Rework invalid cert summary, labeling

- README.md
Useful test/demo site for our plugin and CLI tool.
fixes GH-42
> Add ref links to badssl.com and expired.badssl.com

- doc.go
Instead of replicating the flags from the main README and likely letting them get out of date, point the reader
to the main README where we are concentrating the update efforts.
fixes GH-49
> GoDoc: Point reader to main README for usage info

- cmd/check_cert/main.go
Replace tab escape character with a literal space.
fixes GH-73
> Fix key/value pair thresholds rendering

- cmd/check_cert/main.go
- cmd/lscert/main.go
`check_cert`:
- Explicitly note when we are choosing to skip deferring
calls to `ReturnCheckResults()` and why
- Add missing `defer`/`return` keywords where appropriate to allow
deferred connection close step to run
`lscert`:
- defer `os.Exit` calls (where appropriate) for the same reason
that we defer calling `ReturnCheckResults()` with `check_cert`
fixes GH-76
> Handle closing connection to server

- internal/certs/certs.go
Minor issue with commented out code. I opted to remove the
comments instead of reformatting the lines (was not needed).
> Fix gocritic comment formatting linting error

- cmd/check_cert/main.go
- internal/certs/certs.go
- Update use of `ReturnCheckResults()` method call
- set deferred call at app start return early whenever needed
in order to allow any other deferred functions registered
previously to run, then `ReturnCheckResults()` to return
the final exit code
- Update `GenerateCertsReport` func
- remove leading newline since the `atc0005/go-nagios`
dependency now applies that automatically
- remove hard-coded `\r\n` pattern expected by Nagios, replace
with package constant supplied by `atc0005/go-nagios` package
- Update threshold explanations to remove prefixes now
automatically set by the `atc0005/go-nagios` package
refs GH-81
> Apply changes needed for atc0005/go-nagios v0.5.1 upgrade

- internal/certs/certs.go
That newline is needed to separate out the individual certificates in the chain.
refs GH-81
> Restore newline for certs report

- CHANGELOG.md
Providing binary builds for the v0.1.6 release was mostly a last minute decision. 
I've been wanting to do this for a while, but hadn't yet pulled the trigger. I forced myself to do so with the v0.1.6 release, but the decision was made *after* I had already tagged the release. Updating the CHANGELOG so that the `master` branch reflects the v0.1.6 release via GitHub.
- Explicitly note Go version used to generate binaries
- Fix section order to match existing pattern
- Note binary platforms
> Update CHANGELOG to reflect v0.1.6 binary release

- Makefile
Intended to help trim out unneeded details from misc output.
fixes GH-93
> Add '-trimpath' build flag

- internal/certs/certs.go
This provides the 'Not Before' value to go with the existing 'Not After' value.
fixes GH-102
> Add 'Issued On' label, output to cert summary

- README.md
This blog entry advocates monitoring the entire certificate chain instead of only leaf and intermediate certs. This advice matches what we're already doing; the blog entry covers the problem well.
fixes GH-52
> Add ref advocating monitoring expiration of chain

- Makefile
Update Makefile to reflect correct package for version
variable used to tag builds. This path changed with
the recent refactoring.
refs GH-108
> Makefile: Fix version tagging

- internal/certs/certs.go
- internal/textutils/textutils.go
Explicitly format certificate serial number in colon-delimited hex string OpenSSL text format.
- Add new `certs.FormatCertSerialNumber` function
- format using the colon-delimited hex string OpenSSL text format
- Add new `textutils.InsertDelimiter` function
- used by `certs.FormatCertSerialNumber` function
- usable by other formatting tasks in the future
fixes GH-111
> Fix Certificate Serial Number format

- internal/certs/certs.go
Use combination of `*big.Int` `Bytes` method and `fmt.Sprintf` hex formatting verb instead of `*big.Int` `Text(16)` method call in order to retain leading zero in hex formatted string.
fixes GH-114
> Add back missing leading zero for serial numbers

- README.md
Replace certificate serial numbers in base 10 format with fixed base 16 format.
fixes GH-116
> README: Fix cert serial number in example output

- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
- identify/label self-signed leaf certificates
- collapse `isRootCACert`, `isIntermediateCACert` and
`isLeafCert` functions
- rework cert id logic to fallback to cert chain position
for cases where other attributes (if even available)
are not conclusive
fixes GH-127
> Refactor, "fix" chain position identification

- .github/workflows/lint-and-build-code.yml
- .gitignore
- Makefile
- README.md
- cmd/certsum/main.go
- cmd/certsum/summary.go
- cmd/check_cert/main.go
- cmd/fixsn/main.go
- cmd/lscert/main.go
- doc.go
- internal/certs/certs.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/getters.go
- internal/config/logging.go
- internal/config/validate.go
- internal/net/doc.go
- internal/net/net.go
- internal/textutils/textutils.go
Initial prototype to scan one or more given IP ranges and
and report overview of certificate status. This is a "MVP"
build and considered to be of "alpha" level quality.
Many of the exposed flags, help text and summary output
is subject to change significantly in later releases.
Performance is so-so, with only the initial port scanning
handled in a concurrent fashion; the actual cert retrieval
process is handled one host/port at a time. Unsurprisingly,
this does not scale well for larger IP ranges.
Additionally, specifying partial/non-CIDR IP ranges is not
tested or supported at this time, though it is possible
to specify multiple CIDR ranges for evaluation.
This build also allows for filtering "OK" status hosts and
certs to either increase or reduce the amount of information
provided. …
> Add IP range cert scanner prototype: certsum

- cmd/certsum/main.go
- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/netutils/doc.go
- internal/netutils/net.go
Avoid future collisions with `net` standard library package.
fixes GH-140
> Rename internal/net to internal/netutils

- README.md
- cmd/certsum/main.go
- cmd/range/main.go
- doc.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/getters.go
- internal/config/validate.go
- internal/netutils/net.go
- internal/netutils/types.go
- partial support of "octet range addressing" functionality
as popularized by nmap (not sure if it is the origin)
- dash separator logic supported
- comma separated octet values support (to omit some hosts
from specified specified octet range) *not* implemented
- perhaps in the future
- support for single IP Addresses
- CIDR range support retained
In short, all three formats are how supported. Any value not
matching one of these patterns is rejected. This includes
hostnames and/or FQDNs, which as of this writing are not *yet*
supported.
- refs GH-136
- refs https://nmap.org/book/man-target-specification.html
> certsum: Initial support of partial IP ranges

- README.md
- doc.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/getters.go
- internal/netutils/net.go
- Update flag name to `hosts` to reflect expanded support
- existing `ips` flag retained for now
- Documentation updates to reflect flag name change and
expanded support
- Documentation updates to include updated hostname and
FQDN support and additional examples
- New internal/netutils package-level Error and helper func
for distinguishing between IPv4 and FQDN values
- refs GH-142
- fixes GH-136
- part 2 of 2
> certsum: Add support for hostname and FQDN targets

- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
Break out core functionality into separate functions
dedicated to execution as goroutines:
- collectors (port scan results, cert check results)
- scanners (port scanner, cert scanner)
Still more work to do. This is mostly an attempt to break out
the code for easier review.
refs GH-135
> certsum: Refactor into separate helper funcs

- cmd/certsum/portscan.go
Add missing Msg() invocation for logger call associated with a port scan error. Without this, the logger call fails to emit the intended error message. Because the most common error case for a port scan is an i/o timeout, we emit the error message at debug level and continue scanning the next port.
> Add missing Msg() call for error logging attempt, set to debug log level instead

- cmd/certsum/certcheck.go
The previously deferred call handles this already.
This results in a `panic: sync: negative WaitGroup counter` error when a failure fetching a certificate chain occurs.
> Remove extra wg.Done() call from certScanner

- cmd/certsum/summary.go
- internal/certs/certs.go
- note how many of the discovered certs have issues
- note the type of results display: `all` or `issues only`
The goal is to help tell at a glance what type of output that we're looking at. Less useful when immediately reviewing output after running the command perhaps, but hopefully useful if someone captures the output and records it on a ticket somewhere for later review.
> Increase summary output details

- cmd/certsum/summary.go
While the idea is useful, it doesn't correctly handle early exit when there are no cert issues to report. Collapsing that helper function back into (admittedly redundant) existing summary functions.
> Collapse summary output helper func

- cmd/certsum/summary.go
Only exit early if user did not opt to display valid hosts/certs info in addition to discovered problems.
> Add missing check before early summary output exit

- .gitignore
- README.md
- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/validate.go
- internal/netutils/net.go
A spread of concurrency tweaks and fixes with a scattering
of other improvements. Still more to do, including
simplifying the current design.
- independent limiters for parent/child scanner goroutines
- help prevent potential deadlock when both share the same
rate limiter
- remove shared rate limiter from cert scanner, instead
relying soleyly instead on the port scanner limiter in
an effort to reduce complexity
- Add guard against potentially excessive user-provided
scan rate limit value
- help prevent OS errors re too many open file handles
- update .gitignore to ignore *all* vscode workspace settings
(e.g., plugins) instead of just the main config file
- better handling of channel access, ensuring non-blocking
access whenever not strictly required for intentional rate
limits
- better …
> Refactor concurrency implementation

- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
- internal/netutils/net.go
Remove forced per-host results collection within port scanner and update applicable supporting goroutines to account for the change.
The net result is a simplified version of the changes made for GH-157.
refs GH-135
refs GH-157
> Simplify port scanning concurrency implementation

- internal/config/logging.go
I can't say with certainty, but I believe that this field was always desired and likely dropped at some point during recent refactoring. Adding it back for all project apps.
> Add timestamp to log messages

- .gitignore
- .markdownlint.yml
- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
- cmd/certsum/summary.go
- cmd/check_cert/main.go
- cmd/fixsn/main.go
- cmd/lscert/main.go
- cmd/range/main.go
- go.mod
- internal/certs/certs.go
- internal/config/config.go
At some point the repo was named check-certs instead of check-cert. When the rename occurred I forgot to update the Go module path accordingly. This commit sorts that omission.
> Fix Go module path

- README.md
Other tweaks applied:
- link back to nmap homepage
- spell out details for the `CIDR range` example
fixes GH-175
> Add Overview example to docs

- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
- Extend `ChainStatus` type to bundle cert chain and threshold
values
- Replace `ServiceCheckStatus` field in `ChainStatus` type with
method to provide this text label in addition to the appropriate
exit code
- Simplify `GenerateCertsReport()` func to only require a
`ChainStatus` instead of multiple arguments
- Update `OneLineCheckSummary()` so that an optional flag can be
provided to toggle overall cert chain summary text and so that
multiple other arguments are now replaced by a `ChainStatus`
value
- Provide and use `IsCriticalState()`, `IsWarningState()` and
`IsOKState` `ChainStatus` methods to simplify and fix the logic
for determining the final exit status for the service check.
refs GH-188
> Refactor certs state identification

- README.md
- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- Add new `verbose` flag
- Reassign `v` short flag from `version` to `verbose`
- Expose certificate fingerprints if `verbose` flag specified
- Expose `KeyID` and `IssuerKeyID` if `verbose` flag speciifed
- previously shown by default
- Update README coverage to reflect changes in flags and
example output
fixes GH-192
> Implement verbose flag, expose fingerprints

- cmd/lscert/main.go
- internal/textutils/textutils.go
Move whitespace handling before/after header generation from main lscert app to the `textutils.PrintHeader()` func. This fixes the mismatch between earlier headers and later ones for cert chain and (potential) unparsed cert file data.
fixes GH-203
> Fix inconsistent formatting of lscert headers

- README.md
The recent work to add this support to the `check_cert`
plugin was not noted as intended.
refs GH-193
> Add missing cert file eval support to feature list

- CHANGELOG.md
Update the `rs/zerolog` listing to reflect the correct base version.
> Fix CHANGELOG deps update details

- internal/certs/certs.go
Previous explanation left out details regarding the suffix
used based on whether the certificate is yet to expire or
is already expired.
Remove "this can be made better" comment; since I do not know
explicitly what is wrong with the implementation, leaving a
stray FIXME tag behind doesn't necessarily help.
fixes GH-256
> Fix doc comments for FormattedExpiration func

- internal/netutils/net.go
This allows use of IPv6 IPs as valid targets without special handling.
refs GH-275
> Construct connect string without format string

- cmd/check_cert/main.go
Note that the flag is used to skip hostname verification if the SANs list is found to be empty, not ignore errors
that occur. This text is a holdover from an earlier iteration that I abandoned.
refs GH-276
> Update output for hostname verification failure

- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
- cmd/certsum/summary.go
- internal/certs/certs.go
- internal/config/getters.go
- internal/config/validate.go
- internal/netutils/net.go
- internal/netutils/types.go
- Add SNI support by using hostname (where provided) for cert
evaluation
- List host (where provided) in report output instead of IP Address to
indicate which host was evaluated
- Misc doc comment fixes/clarifications
- Add and use new sentinel errors in `netutils` package in an effort
to provide "hooks" into the underlying cause for various problems
encountered while processing IP Addresses
- Broad replacement of variables indicating IP Addresses with
variables generically indicating hosts or "targets" (since both IP
Addresses and host values are now used internally)
- Expand `netutils.PortCheckResult` type to track host value
separately from the `net.IPAddr` type
- Update cert scanning/evaluation logic to use host value instead of
IP Address if available (SNI support)
- Add minor input …
> Update certsum to use SNI support

- cmd/certsum/certcheck.go
- cmd/certsum/portscan.go
- internal/netutils/net.go
Instead of only returning a partial set of values, return the
`netutils.PortCheckResult` value as-is for potential emission
as summary output.
This resolves the empty host value shown when an attempt to
connect to a port fails.
This logic will likely need further review/refactoring to
better communicate open/closed status.
fixes GH-290
> Fix empty host value by returning full port state

- cmd/certsum/certcheck.go
- cmd/certsum/main.go
- cmd/certsum/portscan.go
- cmd/certsum/summary.go
- internal/certs/certs.go
- internal/config/config.go
- internal/config/getters.go
- internal/netutils/net.go
- internal/netutils/types.go
Prior to the changes applied to resolve GH-273, opting to scan a host
by name that resolved to multiple A records resulted in a scan of each
IP Address. After GH-289, one name resolved to one IP Address only.
This set of changes restores the previous behavior which allows a
single hostname to resolve to multiple records, each a queued scan
target while preserving the newly added SNI support.
Additionally, carry any specified host name/fqdn throughout the
discovery/retrieval process so that log and final report output
indicates which host we're attempting to retrieve certs for along with
the IP Address used to retrieve the certificate chain.
- add `netutils.HostPattern` type to allow grouping a given host
pattern (name, range, or single IP) and any IP Addresses it expands
to along with a …
> Restore support for resolving multiple targets

- internal/config/logging.go
Switch formats from all tools in this project in order to
provide human-friendly debug and error output.
See also:
- refs https://brandur.org/logfmt
- refs https://pkg.go.dev/github.com/rs/zerolog#readme-pretty-logging
- fixes GH-295
> Switch logging output format from JSON to logfmt

- cmd/certsum/certcheck.go
- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
- internal/netutils/net.go
Previously, there was potential for checking a server's port status
using one IP and attempting to retrieve the certificate chain from
another IP Address (due to how the host value was used for cert
retrieval). To provide reliable SNI support we now explicitly specify
both host name/FQDN (if available) and IP Address of target server
when we attempt to retrieve the certificate chain. We set the host
name/FQDN in the client TLS configuration and use the IP Address to
open the connection.
The `lscert` and `check_cert` tools now also explicitly note the host
value and IP Address in summary output.
- add misc debug log statements where previously missing
- expand given host patterns and explicitly use the first resolved IP
for opening a connection to remote server for cert retrieval
- …
> Fix SNI support, list IP/host where cert retrieved

- cmd/check_cert/main.go
- cmd/lscert/main.go
Reduce from WARNING to DEBUG since there are many legitimate scenarios where this is to be expected.
fixes GH-300
> Drop log level of "multiple IPs" message

- cmd/certsum/main.go
- internal/netutils/net.go
- update `netutils.DedupeHosts()` logic to record new hosts
directly instead of attempting to use a non-existent map
value (had the logic inverted)
- update intro text to note unique host patterns and expanded
scan targets, the latter being potentially more relevant in
terms of expected scan queue depth
refs GH-292
> Fix `netutils.DedupeHosts()` logic, intro details

- internal/netutils/net.go
Swap out strings.Trim() with strings.ReplaceAll() calls to apply the original intended logic.
> Fix `netutils.isIPv4AddrCandidate()` logic

- internal/netutils/net.go
The `netutils.DedupeHosts()` function properly dedupes identical given host patterns, but does not dedupe IP Address ranges that may overlap. Because this is a potential source of confusion, this may change in the future.
- refs GH-302
- refs GH-292
> Note issue with `netutils.DedupeHosts()`

- cmd/check_cert/main.go
Emphasize supplying the expected FQDN associated with the certificate via the `dns-name` flag or the `server` flag instead of using the server FQDN.
The prior wording omitted mention of the `dns-name` flag.
> Update hostname verification failure suggestion

- cmd/certsum/main.go
- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/config/config.go
- internal/netutils/net.go
- internal/netutils/types.go
- add `(netutils.HostPattern).Range` field to track whether a given
host pattern is determined to be a CIDR or partial IP Address range
so that we can potentially have client code apply different behavior
depending on whether ranges were given
- change signature of `netutils.ExpandHost()` so that instead of a
collection of HostPattern values being returned we acknowledge that
we should only ever return one HostPattern value that *wraps* the
potential for multiple expanded IP Addresses for a given host
pattern
- collect range expansion values into one slice before bundling as a
new HostPattern value (instead of returning multiple HostPattern
values with one IP in the Expanded collection)
- update `lscert`, `check_cert` to expect a single HostPattern return
value instead of a collection
- …
> Fix IP Address range expansion & update handling

- cmd/certsum/summary.go
Refer to the number of discovered certificate chains *as* chains instead of just "certificates". If we're going to note the total certificates discovered we'll need to count each link in all discovered chains, which we're not yet listing.
> Update summary cert chain count desc/label

- internal/config/logging.go
The `Config.Filename` field is always empty for the `certsum` tool as that tool does not accept that flag.
fixes GH-312
> certsum | remove invalid `filename` logger field

- cmd/lscert/main.go
In addition to verifying the hostname when the `server` flag is specified, also apply hostname verification for a certificate if the `dns-name` flag is used. This matches the logic already used by the check_cert tool.
refs GH-315
> lscert | Verify hostname if dns-name flag is used

- cmd/check_cert/main.go
Move lead-in text immediately after retrieving the certificate chain so that those details are provided regardless of whether hostname verification is successful.
fixes GH-316
> check_cert | Move lead-in text up

- cmd/lscert/main.go
Because the cert may come from a file or a remote system replace mix of "server" and "discovered" with "evaluated" to consistently cover both scenarios.
refs GH-315
> Tweak wording regarding certificate source

- cmd/lscert/main.go
Place the state label before the error message as intended.
fixes GH-323
> Fix lscert SANs service state label position

- cmd/lscert/main.go
Set explicit state label instead of relying on not yet supported dynamic state label/exit code support for SANs list mismatch scenario.
fixes GH-328
refs GH-211
> Fix incorrect state label for SANs list mismatch

- cmd/check_cert/main.go
Label indicated CRITICAL state, but exit code was WARNING. Changed so that both label and exit code are of CRITICAL state.
fixes GH-329
> Fix exit state status code for SANs list mismatch

- cmd/check_cert/main.go
- cmd/lscert/main.go
- internal/certs/certs.go
- update `certs.CheckSANsEntries()` to return the number of
total SANs entries found across all certs in the chain
- update call sites to expect/use updated return values from
`certs.CheckSANsEntries()` function
- add success branch requested/found debug logging call
fixes GH-327
> Fix incorrect SANs list calculations

- internal/certs/certs.go
Instead of iterating over the full certificate chain to determine the number of SANs entries present, focus only on the given certificate.
refs GH-327
refs GH-332
> Update SANs entries evaluation

- cmd/lscert/main.go
Changes made for GH-332 incorrectly moved the SANs list eval
results message out of the error handling path into the shared
path for both successful and failed evaluation.
This commit explicitly handles both scenarios which resolves
having a failure message shown for a successful evaluation and
provides an "eval success" message for that scenario.
- fixes GH-336
- refs GH-211
> Emit correct success/fail SANs eval message

- cmd/check_cert/main.go
- cmd/lscert/main.go
- use DNS Name if specified as the host value given
to the remote service when retrieving certificates chain
- update doc comments explaining SNI support logic for
cert retrieval
- explicitly report host value chosen for cert retrieval
- update debug message's structured log fields to explicitly
note the chosen host value, DNS Name, Server values to
better troubleshoot certificate chain retrieval
refs GH-343
> Use DNS Name if specified as hostVal for SNI

- cmd/lscert/main.go
While I believe that the age threshold details are useful, I no longer believe that displaying them by default is. 
This commit converts those details to DEBUG level log messages so that they're easily retrieved for troubleshooting purposes.
fixes GH-324
> Move lscert age thresholds block to debug messages

- cmd/check_cert/annotations.go
- cmd/check_cert/main.go
Wrap this specific error message with additional details to make clear that the error is due to the plugin runtime exceeding the specified (or default) timeout value.
As a side-effect of adding this support, this commit also provides a baseline Nagios Plugin Performance Data metric that tracks plugin execution time.
fixes GH-285
> Add annotation to `context deadline` error message

- README.md
The README file mentions v0.5.4 and earlier of the plugin, but it is actually v0.5.3 and earlier that the statement applies to.
> Fix version reference for last Go 1.16 build

- cmd/check_cert/annotations.go
It looks like I was merging two comments and didn't finish the thought.
> Fix doc comment language

- internal/config/args.go
- internal/config/config.go
- internal/config/parse.go
- internal/config/validate.go
Add support for accepting a URL via the first positional argument and using it to populate the Config.Server and Config.Port fields.
NOTE: The first positional argument is numbered 0 and accessible via flag.Arg(0).
If Config.Server is already set (presumably via the flag), then skip processing positional argument 0.
fixes GH-378
> lscert | Support parsing a URL via positional arg

- README.md
The prior directions assumed that check_cert would be placed
in the current working directory via go install. Update the
directions to explicitly set `GOBIN` so that the generated
binary will be placed in the current working directory as
intended.
Reference the output from `go help install` to explain why
we are setting GOBIN explicitly.
> Fix go install steps to include valid soruce path

- internal/config/config.go
- internal/config/flags.go
In short, add polish to the help text to better convey expected syntax
and intention of each tool.
- replace shared `config.Usage()` func with closure that
makes use of a app-specific help/usage details
- explicitly reference "pattern" in the usage output for the `lscert`
command
- emit application description just under usage syntax and before flag
help text listing
- explicitly point the reader to the project README for full usage
details (including emitting project URL)
Inspiration drawn from:
- `docker --help`
- `lxc  --help`
- https://github.com/inancgumus/effective-go/blob/de2dd6e07af9fdb65d425b38f2002a8fc99cc50e/ch05/cmd/hit/flags.go
refs GH-385
> Update help text to reflect app-specific usage

- doc.go
Go 1.19 requires link reference syntax, not the standard Markdown link syntax.
> Fix GitHub repo link syntax

- internal/certs/certs.go
Use os.ReadFile() instead of deprecated (as of Go 1.16) ioutil.ReadFile().
> Swap io/ioutil package use for os

- README.md
- internal/config/args.go
- internal/config/flags.go
- internal/config/parse.go
- update README to emphasize that the positional argument for the
`lscert` tool is intended to be a URL pattern, but can be any of
URL, resolvable name or IP Address
- update doc comments to clarify the requirements and behavior of the
positional argument and the `server`, `port` and `filename` flags
- emit positional argument requirements for each of `lscert`,
`check_cert` and `certsum` tools
- at present only the `lscert` tool actually displays relevant
output
fixes GH-384
> Clarify behavior of lscert positional argument

- cmd/certsum/doc.go
- cmd/check_cert/doc.go
- cmd/lscert/doc.go
Add "package" doc file to resolve revive package-comment linting error surfaced by recent linter update.
> Add missing cmd doc files

- README.md
Clarify that CIDR IP ranges are not the only host targets supported by the tool.
> Update certsum overview text

- Makefile
Effectively a NOOP; making this change for consistency with other Makefiles.
> Makefile: Tweak staticcheck pre-install text

- .golangci.yml
Enable additional linters that I already use within the atc0005/go-ci stable
images.
- govet
- staticcheck
> Add additional golangci-lint linters

- .github/workflows/govulncheck.yml
Add new `Vulnerability Analysis` GHAW that executes the experimental govulncheck CLI tool:
- against project source code
- against compiled project binaries
The workflow executes for new/updated Pull Requests and on a weekly schedule.
As with other GitHub Actions Workflows for this project, this Workflow relies upon the Docker images provided by the atc0005/go-ci project.
refs atc0005/go-ci#734
> Add govulncheck GitHub Actions Workflow

- .github/workflows/vulnerability-analysis.yml
Very light research seems to imply that binary scanning is unnecessary if you have access to the source code.
Disabling binary build & scan step for now until I learn differently.
Also, add "on push" event trigger to resolve GHAW linting warning related to the CodeQL analysis job.
refs atc0005/go-ci#734
> govulncheck: Disable binary build & scan step

- internal/config/getters.go
Restore ability to use `disabled` as a valid log level per CLI flag.
fixes GH-427
> Replace duplicate valid log levels entry

- cmd/lscert/main.go
- internal/config/args.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/logging.go
- internal/config/validate.go
Replace `inspecter` with `inspector`.
I suspect that I was at least partially thinking of the Go idiom of naming interfaces with an `er` suffix when I came up with the app type.
refs atc0005/todo#49
> Fix mispelling of Inspector app type

- cmd/check_cert/main.go
When specified by sysadmin, emit host value for cases where the server value is specified as an IP Address and DNS Name is given.
Previous behavior is to list only the IP/port and not indicate what host value was specified when retrieving the certificate.
> Emit host val when set & server is specified as IP

- cmd/lscert/main.go
Add equivalent fix for `lscert` tool to reflect equivalent changes made for the `check_cert` plugin.
This is needed to properly set the host value used when submitting SNI-compatible certificate chain request to the IP Address specified as the server value.
fixes GH-461
> Add host val when set & server is specified as IP

- README.md
- cmd/check_cert/main.go
- cmd/check_cert/perfdata.go
- internal/certs/certs.go
Add performance data metrics to track upcoming expirations and total certificate types (scopes) in the chain:
- `expires_leaf`
- `expires_intermediate`
- `certs_present_leaf`
- `certs_present_intermediate`
- `certs_present_root`
- `certs_present_unknown`
As part of providing these performance data metrics various helper functions were added:
- `certs.NumLeafCerts`
- `certs.NumIntermediateCerts`
- `certs.NumRootCerts`
- `certs.NumUnknownCerts`
- `certs.LeafCerts`
- `certs.IntermediateCerts`
- `certs.RootCerts`
- `certs.OldestLeafCert`
- `certs.OldestIntermediateCert`
- `certs.OldestRootCert`
- `certs.ExpiresInDays`
The README file has been updated to list the purpose of each performance data metric.
As of this commit, failure to collect performance data is emitted as an error message and …
> Add certificate perfdata metrics

- Makefile
New recipes:
- `windows-x86`
- `windows-x64`
- `windows` (a "wrapper" around the two arch-specific options)
- `linux-x86`
- `linux-x64`
- `linux` (a "wrapper" around the two arch-specific options)
refs GH-471
> Makefile: Add arch, OS-specific build recipes

- Makefile
Add new Makefile recipes common to other projects
that I maintain:
- gogeninstall
- installs dependencies needed for `go generate` usage
- depsinstall
- installs build dependencies (e.g., nfpm)
- calls gogeninstall recipe
- intended as the "entry point" for common/shared GHAWs
refs GH-471
> Add gogeninstall, depsinstall Makefile recipes

- Makefile
Based on some light reading, inconsistent use of variable types is causing not only a performance hit in some cases, but likely some unreliable results based on how the recursive expanded variable type is resolved.
For any case where the values are fixed or should be fixed after an initial interpolation those variables should be updated to the simply expanded type.
This commit reflects those changes.
fixes GH-476
> Makefile: Replace most recursively expanded vars

- Makefile
- generate checksum files for *all* deb packages
- formatting changes for rpm checksum file generation (NOOP)
- switch from unqualified path in `OUTPUTDIR` Makefile variable to fully-qualified `ROOTPATH` variable
- NOTE: More of these changes pending
refs GH-471
> Update checksum generation

- Makefile
Switch from `OUTPUTDIR` to `ROOT_PATH` so that commands are using fully-qualified paths instead of relative paths.
refs GH-471
> Use fully-qualified root path vars

- Makefile
If the current branch & commit does not match 1:1 with a tag the command used to build the `RELEASE_TAG` Makefile variable emits an error.
This commit mutes this error output since it will cause more confusion and use a static `PLACEHOLDER` string in its place.
refs GH-471
> Mute error from release tag exact match attempt

- cmd/check_cert/perfdata.go
- add `min` field value for `expires_leaf` metric
- add `min` field value for `expires_intermediate` metric
fixes GH-475
> Add `min` expiration value to `expires_*` perfdata

- Makefile
- README.md
- split arch/os-specific recipes into separate tasks
- building assets
- creating checksum files for assets
- compressing assets (NEW)
- formatting tweaks to output
- lowercase subtasks
- minor tweaks to "completed" messages to better match specific recipe (e.g., don't say "build" for non-build tasks)
- rework package build and release-build recipes to share work
- don't rebuild assets
- postpone generating download links until all assets are available
- update README
- note replacement Makefile recipes to achieve previous functionality (sans checksum files)
- note need to decompress (compressed) binaries before deploying them
- note optional DEB and RPM packages in lieu of manually deploying binaries
fixes GH-470
> Makefile: Compress binaries & use static filenames

- .github/workflows/lint-and-build.yml
- .gitignore
- Makefile
- cmd/certsum/main.go
- cmd/certsum/winres/winres.json
- cmd/check_cert/main.go
- cmd/check_cert/winres/winres.json
- cmd/lscert/main.go
- cmd/lscert/winres/winres.json
- dependabot/tools/go.mod
- dependabot/tools/tools.go
Use tc-hib/go-winres and JSON config files to embed metadata (e.g., version, description) into Windows executables via `go generate`.
Related changes:
- add winres.json files to provide metadata to be embedded into generated Windows executables
- add `go generate` directives to main.go files
- add dependabot/tools entry for tc-hib/go-winres
- add .gitignore entry for .syso files created by tc-hib/go-winres
- Update Makefile build recipes to run `go generate` for Windows builds
- Update GHAW to indicate to shared/imported workflow that
gogeninstall Makefile recipe is needed for builds
fixes GH-473
> Add version details to Windows executables

- Makefile
- generated packages are now placed into separate subdirectories
- `goclean` recipe updated to reflect new generated package subdirs
- add `packages-dev` recipe to generate dev build packages
- add `dev-build` recipe to handle dev release related tasks
- currently dev packages build, download links files
- rename existing `packages` recipe to `packages-stable`
- add `packages` recipe to cover both dev & stable package builds
- update `package-links` recipe to handle updating download links files for both dev and stable packages
- NOTE: May break this into separate recipes later
- use `set -e` with various recipes to help surface (and abort when encountered) error with bulk (loop) actions
> Update Makefile recipes for dev/stable releases

- Makefile
Evidently when uploading packages containing a tilde character in the filename GitHub replaces them with a dot character.
This PR updates the package-links recipe to perform this substitution when generating package download links.
fixes GH-493
> Substitute tilde character in generated pkg download URLs

- Makefile
Download links for windows x64 binaries were generated with incorrect suffix.
> Fix windows-x64 binary links

- Makefile
In short, this commit changes the Makefile logic to move from generating filenames like these:
```
check-cert-0.11.0~1-g6bc2774.x86_64.rpm
check-cert-0.11.0~1-g6bc2774.x86_64.rpm.sha256
check-cert_0.11.0~1-g6bc2774_amd64.deb
check-cert_0.11.0~1-g6bc2774_amd64.deb.sha256
```
to names like:
```
check-cert-0.11.0-1-g6bc2774.x86_64.rpm
check-cert-0.11.0-1-g6bc2774.x86_64.rpm.sha256
check-cert_0.11.0-1-g6bc2774_amd64.deb
check-cert_0.11.0-1-g6bc2774_amd64.deb.sha256
```
If the builds are performed with uncommitted local changes the "dirty" string is included to make that clear.
Example:
```
check-cert-dev-v0.11.0-2-g803b81f-dirty.x86_64.rpm
check-cert-dev-v0.11.0-2-g803b81f-dirty.x86_64.rpm.sha256
check-cert-dev-v0.11.0-2-g803b81f-dirty_amd64.deb …
```
> Update package filename generation patterns

- dependabot/docker/builds/Dockerfile
The dependabot/docker/builds/Dockerfile was set to use this image:
- go-ci-oldstable-build-v0.8.0-2-g87114607
and earlier an updated image was released, but Dependabot refused to recognize it as an update:
- go-ci-oldstable-build-v0.8.1-0-ga96dbbdb
I've released alternate tags without the "long" git tag details closer to what Dependabot parses for other Dockerfiles that it monitors.
Updating the Dockerfile to that simpler version tag as a troubleshooting step.
> Update versioned build image source syntax

- Makefile
The user executing the build tasks has permission to execute them without elevated privileges.
> Remove use of sudo for Docker commands

- .github/workflows/lint-and-build.yml
- Makefile
The distinction between "go generate" and general build dependencies isn't important enough to maintain separate Makefile recipes.
refs https://github.com/atc0005/shared-project-resources/issues/71
> Replace gogeninstall recipe with depsinstall

- Makefile
Update Makefile to replace `VERSION` variable set via `git describe --always --long --dirty` with `REPO_VERSION` variable. This variable is first looked for externally (e.g., to allow being set via GitHub Actions) before being set to either the output from running `git-describe-semver` or a fallback string of `YOU_NEED_TO_RUN_depsinstall_makefile_recipe` to suggest to next steps for installing required build dependencies.
The RELEASE_TAG variable is still provided via `git describe --exact-match --tags` to force an exact match of a git tag in order to match what is used with a GitHub project release version. This value is used with download links entries in generated `*-links.txt` files.
> Use git-describe-semver for generating release ver

- internal/certs/certs.go
The `ErrX509CertReliesOnCommonName` sentinel error is used by this project to aid in detecting this specific error scenario. While performing a string match for this error works at present, it feels brittle and subject to break in the future if the error text should change.
By opening a RFE/proposal in the upstream Go project, we may gain a supported/stable approach for matching the error in the future.
refs GH-520
> Add TODO to open upstream RFE re unexpected error

- internal/certs/validation-hostname.go
- internal/config/getters.go
- update handling of `ErrX509CertReliesOnCommonName` error condition to respect explicit request from sysadmin to ignore validation results
- helper func doc comments cleanup
- clarify certs.ValidateHostname behavior
- emphasize that explicit request from sysadmin to ignore validation results is respected
- note why check results are ignored when the SANs list is found to be empty (when requested)
fixes GH-505
> Fix hostname validation opt-out behavior

- cmd/certsum/summary.go
- cmd/check_cert/validate.go
- cmd/lscert/main.go
- internal/certs/certs.go
- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-sans.go
Add and use `certs.CertChainValidationOptions` struct to specify validation settings for use by `certs.Validate*` funcs. This provides a common Options struct to help prevent growing the parameters list excessively (e.g., as additional validation support is added in the future).
Client code for the `certs.Validate*` funcs has been updated to reflect these changes.
This set of changes is being made in preparation for supporting ignoring of expired intermediate and root certs.
refs GH-397
> Use certs.CertChainValidationOptions struct

- cmd/check_cert/validate.go
- The wrong `CertChainValidationOptions` field was set when requesting hostname validation
- the `IgnoreValidationResultSANs` field was set instead of the `IgnoreValidationResultHostname` as intended
- Explicitly log `CertChainValidationOptions` values
- log field values prior to each validation check to aid with future troubleshooting
- refs GH-525
> Fix disabling of hostname validation

- Makefile
Add newline when emitting filename so that multiple matching files in the release_assets path are not (unintentionally) concatenated together when building a list of files to generate checksums for.
> Fix Makefile find command printf syntax

- cmd/check_cert/perfdata.go
- internal/certs/certs.go
- remove the limiter that disallowed negative expiration value (returning 0 as the baseline)
- remove the `min` perfdata field value of 0 indicating that this was as low as the metric value could go
fixes GH-529
> Permit negative expiration perfdata values

- packages/dev/nfpm.yaml
- packages/dev/scripts/rpm/postinstall.sh
- packages/stable/nfpm.yaml
- packages/stable/scripts/rpm/postinstall.sh
- Assert that SELinux is enabled before using `chcon` to apply context to installed plugin
- Add dependency on `libselinux-utils` package
fixes GH-509
> Update SELinux context handling in RPM packages

- cmd/check_cert/main.go
Abort with UNKNOWN state when:
- failing to generate performance data
- failing to add/gather generated performance data
refs GH-464
> Use UNKNOWN state for perfdata add failures

- cmd/check_cert/main.go
Update handling of invalid flags/values to use an UNKNOWN exit state to comply with Nagios Plugin Guideline
recommendations.
refs atc0005/check-cert#464
refs atc0005/todo#55
refs https://nagios-plugins.org/doc/guidelines.html
> Use UNKNOWN state for invalid command-line args

- cmd/check_cert/main.go
Per Nagios Plugin Guidelines, we return a WARNING state when parsing/encountering unexpected certificate file content instead of a CRITICAL state (reserved for "not running" or "above critical threshold" results).
refs GH-464
https://nagios-plugins.org/doc/guidelines.html
> Use WARNING state for unexpected cert file content

- Makefile
The `check-cert-dev` DEB and RPM packages are now generated alongside the `check-cert` DEB and RPM packages. This is to allow configuring a monitoring instance to have "test" service checks that use a "dev" command definition/plugin in addition to the standard/normal/prod command definition/plugin. This allows testing new plugin releases gradually before deploying a new stable version (used by potentially hundreds of service checks).
fixes GH-541
> Generate dev packages for release builds

- cmd/lscert/winres/winres.json
The InternalName field was incorrectly set to `check_cert` instead of `lscert` as intended.
> Fix lscert Windows binary InternalName metadata

- cmd/check_cert/main.go
This was missed when recently refactoring exit state handling.
refs GH-464
refs GH-536
> Add missing return for perfdata add failure case

- .dockerignore
- Makefile
- dependabot/docker/builds/Dockerfile
- update builder image Dockerfile
- copy project/repo content into container at build time - explicitly changing owner:group to `builduser`
- explicitly create new `builduser` user and group
- this is explicitly used for Docker-based builds
- set `/builds` as the working directory
- add new `.dockerignore` file to exclude the same items as the `.gitignore` file
- set Git `safe.directory` logic at system level
- update Makefile recipes
- add separate docker/podman variants of container-based project build recipes - each uses slightly different logic to achieve rootless container execution
- explicitly emit the tool used to perform specific tasks
- this can be useful to help explain why a generated builder image does not appear in the `docker image ls` output as a sysadmin might expect (if …
> Add rootless container builds via Docker/Podman

- cmd/certsum/certcheck.go
- cmd/certsum/portscan.go
This function (used as a goroutine) previously received the rate limiter channel intended for this purpose, but failed to make use of it.
The revive linter upgraded in the golangci-lint v1.52.0 release flagged the channel as an unused parameter which surfaced this issue.
This commit implements rate limiting for this function similar to what is already applied to the portScanner function.
Small tweaks have been made to debug logging for both functions to help troubleshoot potential future issues with adding/removing rate limiting reservations.
fixes GH-552
> Implement certScanner rate limiting

- internal/config/logging.go
Returning error directly instead of applying conditional check (as an early exit point in case we were to extend the Config.setupLogging func later).
fixes GH-553
> Fix "if-return" revive linting error

- cmd/check_cert/validate.go
- cmd/lscert/main.go
- internal/certs/validation-sans.go
Presumably the DNS Name parameter was used for SANs validation at some point, but is correctly identified by the revive linter as not being currently used.
Remove it until needed.
fixes GH-555
> Fix "unused-parameter" revive linting error

- internal/config/config.go
- internal/netutils/net.go
Resolve two of four linting issues identified by the errwrap linter.
The remaining two linting issues appear to be false-positives and will be considered as part of future work.
refs GH-564
> Fix some errwrap linting errors

- internal/certs/certs.go
If there are days remaining join it with hours remaining, otherwise use just the hours remaining for the formatted expiration value.
fixes GH-579
> Conditionally join days/hours before expiration

- internal/config/config_test.go
- internal/config/constants.go
- internal/config/validate.go
Previous validation unintentionally allowed specifying 0 as the destination TCP port.
While useful for a server application (auto-bind behavior) this is not useful for a client application intended to connect to a specific target port.
Update validation to disallow specifying zero as a TCP port value and offer feedback indicating the valid start/end port range, including brief examples of common ports.
> Fix TCP port flag validation

- cmd/check_cert/annotations.go
This has been observed as caused by incorrectly specified target port and/or a stopped remote certificate-enabled service.
fixes GH-591
> Add advice for `connect: connection refused` error

- cmd/check_cert/annotations.go
Range over function closure argument instead of error collection from outside of function body.
> Fix helper function closure collection evaluation

- cmd/check_cert/annotations.go
- cmd/check_cert/main.go
Switch from local error annotation implementation to upstream implementation. The project specific error advice is commented out instead of completely removed for the time being.
> Update error annotation implementation

- internal/config/constants.go
- internal/config/flags.go
- internal/config/validate.go
- internal/netutils/net.go
- collapse split format strings to combine text and remove confirmed duplication
- fix goconst linting error for shorthand suffix by creating shared constant
> Fix goconst linting errors

- internal/certs/certs.go
Add error handling for empty PEM data bytes slice scenario that can occur when evaluating an effectively empty certificate file.
refs https://github.com/smallstep/certinfo/pull/38
> Improve cert file parsing

- internal/textutils/textutils.go
Apply base 16 string formatting to entire byte slice instead of to each individual byte within the slice. This retains the expected leading zero for formatted bytes.
We also reuse textutils.InsertDelimiter to provide formatting of the hex string instead of duplicating the logic.
I left a commented out hotfix for later review/consideration (or cleanup).
- fixes GH-706
> Fix textutils.BytesToDelimitedHexStr logic

- cmd/certsum/certcheck.go
Fix revive `unused-parameter` linting error caused by unintentional use of a variable from the goroutine's parent scope.
- fixes GH-764
> Fix linting error and potential race condition

- README.md
Tweak wording to note that `go build` without qualifying build environment variables (e.g., `GOOS` and `GOARCH`) results in building for the current operating system and architecture.
Explicitly note amd64 build options for Windows and Linux platforms.
Explicitly note build option for Linux ARM64 platform.
refs GH-769
> Update README to explicitly mention arm64 builds

- internal/certs/certs.go
Update `certs.ExpirationStatus` to provide remaining cert lifetime percentage at the end of the expiration status line. This results in the life remaining percentage being displayed for all certificates in the chain.
- GH-807
> Add life remaining percentage to expiration status

- README.md
- cmd/check_cert/perfdata.go
- internal/certs/certs.go
New performance data metrics:
- `life_remaining_leaf`
- `life_remaining_intermediate`
New helper funcs:
- `certs.MaxLifespan`
- `certs.MaxLifespanInDays`
- `certs.LifeRemainingPercentage`
- `certs.LifeRemainingPercentageTruncated`
Update README to list new performance data metrics.
- fixes GH-792
> Add certificate lifetime metrics

- internal/certs/certs.go
Surfaced by the `unstable` linting image configuration and recent `gopls` releases.
- GH-816
- GH-817
> Fix nilness govet linting errors

- cmd/certsum/summary.go
- internal/certs/validation-results.go
- internal/certs/validation-sans.go
- internal/config/flags.go
Resolve `return value of fmt.Fprintf is not checked`` errors by
explicitly discarding return values (potential error, bytes written)
since we do not need them and the potential for failure (in this
particular use case) is *highly* unlikely.
> Fix errcheck linting errors

- internal/certs/certs.go
Minor tweak to the "SANs entries" line in summary output to include the total count of SANs entries for the cert or "None" in place of the previous set of empty brackets.
refs GH-630
> Add SANs list count to cert summary output

- Makefile
- README.md
- cmd/check_cert/main.go
- cmd/cpcert/doc.go
- cmd/cpcert/filter.go
- cmd/cpcert/main.go
- cmd/cpcert/print.go
- cmd/cpcert/winres/winres.json
- cmd/lscert/main.go
- internal/certs/certs.go
- internal/config/args.go
- internal/config/config.go
- internal/config/constants.go
- internal/config/flags.go
- internal/config/getters.go
- internal/config/logging.go
- internal/config/parse.go
- internal/config/validate.go
- packages/dev/nfpm.yaml
- packages/stable/nfpm.yaml
The new `cpcert` prototype tool supports copying certificate chains from a server or input file and optionally filtering to specific certificate types before saving to an output file (PEM format).
Config validation logic has been refactored to help the new tool fit within the project without duplicating existing work.
Overall, this is a "MVP" build and while usable, it should be considered to be of "alpha" level quality. Please report issues that you encounter.
Many of the exposed flags, help text and summary output are subject to change significantly in later releases.
Feedback on the new `cpcert` tool is welcome:
https://github.com/atc0005/check-cert/discussions/963
- refs GH-171
- refs GH-956
> Add new tool to support copying/filtering certs

- cmd/lscert/main.go
- internal/certs/certs.go
Update hostname validation logic to ignore the result if a leaf certificate is not present in the given certificate chain OR if the `dns-name` flag was not used. Add a slight addendum/note explaining what is needed (if a leaf cert is present) or that the check is unsupported (if no leaf cert is present).
Add new functions to the `internal/certs` package to quickly answer whether any certificate of the specified type is present within a given certificate chain:
- `HasLeafCert`
- `HasIntermediateCert`
- `HasRootCert`
- GH-952
> Update `lscert` hostname validation behavior

- README.md
- note OS / Go release combination limitations
- list Makefile recipes to target specific macOS build options
refs GH-967
> Add doc coverage for macOS binaries

- Makefile
- README.md
- update build process (Makefile) to generate binaries for supported macOS architectures
- `darwin/amd64`
- `darwin/arm64`
- update README
- note OS / Go release combination limitations
- list Makefile recipes to target specific macOS build options
- fixes GH-967
> Add support for macOS binaries

- internal/certs/validation-hostname.go
Drop the doc comments explaining the intent and earlier `ignored` field setting which applied before the changes to correct the behavior were introduced.
refs GH-358
refs GH-522
> Remove invalid hostname val opt-out notes

- cmd/check_cert/paypload.go
This field would allow the sysadmin to omit the full list of SANs entries to conserve plugin output size and still indicate the number of SANs entries present for a certificate. This helps prevent a scenario where an empty SANs entries collection implies that no SANs entries were provided (though the `CertificateChainIssues.MissingSANsEntries` field if checked would dispel that notion) but also provides the number for use in display or for metrics purposes.
refs GH-1045
> Add SANs entries count to cert metadata payload

- cmd/check_cert/paypload.go
This field will be used to report what algorithm was used to sign a certificate. Weak signature algorithms are considered a vulnerability for remediation, so surfacing this value is useful for reporting (and other) purposes.
fixes GH-1044
> Add Cert Signature Algorithm to cert payload

- internal/certs/certs.go
List alongside cert status and expiration details.
fixes GH-1037
> Add Certificate Signature Algorithm to output

- cmd/check_cert/paypload.go
Use full certificate chain as intended instead of filtered collection that sysadmin selected for service check evaluation via implicit or explicit evaluation options.
refs GH-1065
> Fix certificate chain payload generation input

- cmd/check_cert/paypload.go
- internal/certs/certs.go
This can be used to surface weak signature algorithms used to sign certificates in a chain.
refs GH-1058
> Add WeakSignatureAlgorithm to cert payload

- cmd/check_cert/paypload.go
- internal/certs/certs.go
Previous implementation of evaluation logic in GH-1070 was incomplete and did not take into consideration whether cert was a root certificate (as intended).
refs GH-1063
> Explicitly list root cert signature algorithms as ignored

- cmd/check_cert/paypload.go
- internal/certs/certs.go
Refactor logic to allow "helper" functions to optionally evaluate (but ignore by default), explicitly note when weak signature is detected but ignored.
refs GH-1063
> Rework listing root cert sig algorithm as ignored

- cmd/check_cert/paypload.go
Base count on original certificate SANs list and not potentially empty list (if sysadmin opts to skip including them in the output).
refs GH-1045
> Fix SANs entries count payload field logic

- cmd/check_cert/main.go
- cmd/check_cert/paypload.go
Update logic so that a failed attempt to generate & add a certificate metadata payload results in halting plugin execution (vs recording the error for display in output).
> Rework error handling for cert payload generation

- internal/netutils/net.go
Replace explicit Error() method call on lookup error to switch from returning a string suffix to including an additional error by way of a second error wrapping verb (Go 1.20+).
refs GH-564
> Fix errwrap linting error

- cmd/check_cert/main.go
Add missing `if err != nil` check intended for inclusion with 98d62222cd92e1807237f0cf281d3172a4a5c4bd. This is what I get for multitasking.
> Fix error handling for cert payload generation

- cmd/check_cert/main.go
- go.mod
- go.sum
- vendor/github.com/atc0005/go-nagios/CHANGELOG.md
- vendor/github.com/atc0005/go-nagios/nagios.go
- vendor/modules.txt
This metric is primarily used to audit current plugin output size values before enabling the generation of a certificate metadata payload (which increases the output size quite a bit).
> Enable plugin output size metric

- internal/certs/certs.go
Emphasize that the returned value is intentionally truncated since the result may be used to calculate when a sysadmin is notified of impending expiration (and not just for display purposes).
> Note why certs.MaxLifespanInDays truncates result

- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-results.go
- internal/certs/validation-sans.go
Extend the CertChainValidationResult interface to require an implementation of ValidationStatus method.
Add/Update implementation for each of:
- ExpirationValidationResult
- SANsListValidationResult
- HostnameValidationResult
Update the ExpirationValidationResult implementation to use existing helper methods to determine validation status instead of repeating expiration checks.
Add `ValidationStatus*` keyword constants for use with all CertChainValidationResult implementations.
> Add ValidationStatus to CertChainValidationResult

- internal/certs/certs.go
These changes are intended as groundwork towards implementing upcoming chain order validation support.
- add new helper functions
- `certs.verifySignature`
- `certs.verifySignatureMD5WithRSA`
- `certs.verifySignatureSHA1WithRSA`
- `certs.verifySignatureECDSAWithSHA1`
- remove `certs.isSelfSignedMD5WithRSA helper func
- refactor `certs.isSelfSigned` to drop use of that func and use `certs.verifySignature` helper func directly
- update `certs.verifySignature` func doc comments to emphasize intentional handling of certificates signed with outdated signature algorithms that current Go releases reject with the `x509.InsecureAlgorithmError` error
- move `nolint:gosec` directives to same line as "problem" imports to prevent automatic import reordering from separating `nolint` directives from …
> Refactor self-signed signature handling

- go.mod
- go.sum
- vendor/github.com/atc0005/cert-payload/CHANGELOG.md
- vendor/github.com/atc0005/cert-payload/format/internal/shared/shared.go
- vendor/github.com/atc0005/cert-payload/internal/certs/certs.go
- vendor/modules.txt
Pull in recent changes for testing:
- adjust misordered chain logic
- refactor self-signed signature handling
See also:
https://github.com/atc0005/cert-payload/releases/tag/v0.7.1-alpha.1
> Update atc0005/cert-payload to v0.7.1-alpha.1

- internal/certs/certs.go
- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-sans.go
Update santity checks switch blocks for SANs, Expiration and Hostname validation to return `ErrIncompleteCertificateChain` error value when cert chain is of length 0.
> Return incomplete chain error when chain is empty

- internal/certs/validation-expiration.go
Update `certs.ValidateExpiration` function to generate a `ExpirationValidationResult` value in its entirety instead of splitting before/during/after the switch block.
This matches the structure used by other `CertChainValidationResult` implementations.
> Refactor ExpirationValidationResult checks logic

- internal/certs/validation-hostname.go
Bump from minimum to maximum to reflect how severe the issue is.
fixes GH-1152
> Bump priority for unhandled hostname verify fail

- internal/certs/validation-sans.go
Exit early if no list provided and the option to ignore this validation check (default setting) is specified.
> SANs List validation early exit when list is empty

- internal/textutils/textutils.go
Swap out use of `len` (performs bytes length calculation) with `utf8.RuneCountInString` (char length calculation). While the two provide identical results for *most* cases (where ASCII characters are given), using `utf8.RuneCountInString` looks to be the correct approach to use here (where non-ASCII characters *could* be provided at some point in the future).
> Update `textutils.PrintHeader` length logic

- internal/certs/validation-sans.go
Update `SANsListValidationResult.String` method to drop `SANsListValidationResult.StatusDetail` method call; the caller can explicitly use `SANsListValidationResult.StatusDetail` or indirectly receive those details via the
`SANsListValidationResult.Report` method.
> Reduce verbosity of the `SANsListValidationResult.String` method

- internal/certs/validation-results.go
Update `CertChainValidationResult` interface doc comments to clarify that implementations should not rely on
leading/trailing whitespace to be retained in output for `Status`, `Overview`, `StatusDetail`, `String` and `Report` method output.
Update `CertChainValidationResults.Report` method to explicitly trim leading/trailing whitespace in called `Report` method and add explicit trailing `nagios.CheckOutputEOL` value.
> Clarify CertChainValidationResult output control

- internal/certs/validation-expiration.go
Adjust priority for expiring leaf or intermediate certificates from minimum to medium to better reflect importance of this result contrasted against other validation checks.
> Adjust ExpirationValidationResult priority

- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-results.go
- internal/certs/validation-sans.go
Update doc comments regarding behavior of each implementation for `CertChainValidationResult.Priority` and the interface itself to clarify intent behind the logic.
> Clarify CertChainValidationResult.Priority

- README.md
- cmd/check_cert/main_test.go
- cmd/check_cert/perfdata.go
- cmd/check_cert/validate.go
- cmd/lscert/main.go
- internal/certs/advice/root-cert-found.txt
- internal/certs/advice/sectigo-email-download-links.txt
- internal/certs/certs.go
- internal/certs/validation-chain-order.go
- internal/config/config_test.go
- internal/config/constants.go
- internal/config/getters.go
- internal/config/logging.go
This set of changes applies to both the `check_cert` plugin and the `lscert` CLI tool. While the primary focus is adding a prototype implementation of "chain order" validation logic, other ergonomic and display changes have been applied to the `lscert` tool. Some of those changes are likely to be refined further in near future releases as additional validation checks are applied.
- update `check_cert` plugin
- add new `Chain Order` validation type
- assert that leaf certificate is first in chain, followed by the intermediate which signed it, a potential second intermediate which signed the former and so on
- current implementation objects to a single leaf cert in a chain, though this behavior may be moved to a separate validation check specific to intermediates
- current implementation …
> Initial implementation of chain order validation

- internal/config/constants.go
Update doc comments to remove indicator that this timeout only comes into play after confirming TCP port is open (while that may apply to certsum it does not currently apply to other tools in this project).
refs GH-380
> Update doc comments for default connection timeout

- cmd/check_cert/validate.go
- cmd/lscert/main.go
- internal/certs/validation-chain-order.go
This value appears to have been mistakenly retained when copying/pasting/modifying an existing implementation of the `CertChainValidationResult` interface to create the `ChainOrderValidationResult` implementation.
> Drop OmitSANsEntries from Chain Order validation

- internal/certs/certs.go
This allows the function to be used with two age thresholds as before but also now with just one age threshold.
The switch statement logic has also been simplified, explicitly skipping over expired certs instead of excluding them using via more complex boolean logic.
> Refactor HasExpiringCert func to use variadic args

- internal/certs/validation-chain-order.go
- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-sans.go
This alters a recent change in behavior to return
the `ErrIncompleteCertificateChain` error in place of the more generic `ErrMissingValue` error value previously used.
Now, we return the more appropriate `ErrNoCertsFound` error value from all current validation checks when an empty certificate chain is detected.
Some further work is needed to update WARNING and CRITICAL state detection to look for an `ErrNoCertsFound` error and treat it as an appropriate state.
- refs GH-1155
- refs GH-1167
> Return ErrNoCertsFound error when chain is empty

- README.md
- cmd/check_cert/main_test.go
- cmd/check_cert/validate.go
- cmd/lscert/main.go
- internal/certs/advice/root-cert-found.txt
- internal/certs/certs.go
- internal/certs/validation-chain-order.go
- internal/certs/validation-helpers.go
- internal/certs/validation-root.go
- internal/config/config_test.go
- internal/config/constants.go
- internal/config/getters.go
- internal/config/logging.go
This set of changes applies to both the `check_cert` plugin and the `lscert` CLI tool. These changes borrow heavily from recent work for the initial implementation of the `Chain Order` validation check. As with that implementation, this set of changes is subject to change as work to implement further validity checks (and refactor existing ones) continues.
- update `check_cert` plugin
- add new `Root` validation type
- assert that no root certificates are in the chain
- remove 'note' from the `Chain Order` validation check when a root certificate is found (now handled by this check)
- extend tests to cover new validation type
- update `lscert`
- incorporate new validation check
- incorporate the same "advice" output that the `check_cert` plugin now emits for `Root` validation problems
- …
> Initial implementation of `Root` cert validation

- internal/certs/validation-expiration.go
Add back dropped `HasExpiredCert` check to the `ExpirationValidationResult.IsCriticalState` method. This was unintentionally removed as part of a recent refactoring effort.
- GH-1196
> Fix CRITICAL expiration state detection

- dependabot/docker/go/Dockerfile
Switch to pre-release Go 1.24 series ahead of official stable release.
> Switch dev branch to Go 1.24rc1

- internal/certs/validation-expiration.go
Replace unintentional check of the first SANs entry's length with the intended length check of the collection itself.
- fixes GH-1235
> Fix SANs length check in expiration validation
