- README.md
Fix some typos that crept in from recent edits.
Tweak wording to (hopefully) read a little clearer.
> README: Fix misc typos

- README.md
This commit brings the examples up to date with the latest changes in the v0.1.2 release.
fixes GH-45
> Refresh examples to reflect v0.1.2 changes

- go.sum
- vendor/github.com/atc0005/go-nagios/.golangci.yml
- vendor/github.com/atc0005/go-nagios/CHANGELOG.md
- vendor/github.com/atc0005/go-nagios/Makefile
- vendor/github.com/atc0005/go-nagios/README.md
- vendor/github.com/atc0005/go-nagios/go.mod
- vendor/modules.txt
> Update vendored deps post PR 68

- go.sum
- vendor/github.com/atc0005/go-nagios/CHANGELOG.md
- vendor/github.com/atc0005/go-nagios/README.md
- vendor/github.com/atc0005/go-nagios/nagios.go
- vendor/modules.txt
Update atc0005/go-nagios from v0.4.0 to v0.5.1.
NOTE: There are code-level changes that are still needed
to accomodate this dependency bump. I will handle those
with a follow-up set of changes.
refs GH-81
> Update vendored deps post PR 81

- internal/config/logging.go
- send to stdout for CLI app
- send to stderr for Nagios plugin
fixes GH-123
> Update logging config to route messages properly

- internal/certs/certs.go
- assume that self-signed signature validation success is
"good enough" to ID a v1 or v2 cert as a CA cert
- consider the presence of `X509v3 Extended Key Usage`
extension values as an indicator of a non-CA cert
- consider the presence of `Certificate Signing` or `CRL signing`
`X509v3 Key Usage` values (and without presence of
`X509v3 Extended Key Usage` extension) to indicate CA cert
Any other pattern for self-signed certs successfully validated
with their own public key is considered a non-root CA cert.
- assert that cert with matching Issuer and Subject values is
*not* an Intermediate cert
- don't apply signature check against itself, but otherwise
apply all other root CA checks
- assert IsCA field not set
- consider the presence of `X509v3 Extended Key Usage`
extension values as an …
> Extend cert type/position identification checks

- internal/certs/certs.go
Borrow heavily from standard library `x509.checkSignature` function to implement support for verifying MD5-RSA cert signatures.
A MD5-RSA signature was encountered while checking a 2010 self-signed certificate generated by a HP printer.
fixes GH-130
> Add support for verifying MD5-RSA signatures

- cmd/certsum/main.go
- cmd/certsum/summary.go
- internal/certs/certs.go
Drop results table if no problems were encountered, explicitly note as much to help clarify final results.
fixes GH-143
> certsum: Omit results table if no cert probs found

- cmd/certsum/main.go
Note the total time for each of port scans and cert checks.
> Add timing info to step completes msgs

- cmd/certsum/main.go
Initial implementation. Will refactor further to feather cert checks directly into the port scanning process.
refs GH-135
> certsum: Update cert checks to run concurrently

- README.md
Update output to reflect fixed chain status logic.
fixes GH-188
> Refresh examples in README for Nagios plugin

- cmd/check_cert/main.go
> Fix invalid formatting interpolation

- internal/certs/certs.go
Use upstream dependency's copy of type.
refs atc0005/go-nagios#80
refs GH-225
> Replace bundled ServiceState type

- internal/config/config.go
- internal/netutils/net.go
> Fix var-declaration revive linter errors

- internal/config/logging.go
Remove fields specific to the `inspector`, `plugin` app types:
- `port`
- `server`
Add `ports` specific to the `scanner` app type.
The implementation could probably use more polish, but this
works for now and offers easier customization for exposing
further common, app type-specific fields later.
fixes GH-286
> Remove invalid logger fields

- cmd/check_cert/main.go
- cmd/lscert/main.go
- consistent capitalization of log messages
- add a few additional debug log messages noting when an action is about to take place
- prune outdated doc comment
> Minor logging & doc comment tweaks

- README.md
- minor tweaks/corrections
- refresh examples
- note logging output format change
- remove status column for tools list
- all tools are usable in their current state and future development efforts don't easily fall into a labelled state
> Update README for v0.7.0 release

- cmd/lscert/main.go
These doc comment updates were intended for the last PR, but I committed my changes before missing that I had failed to stage these as well.
refs GH-315
> lscert doc comment tweaks

- cmd/check_cert/annotations.go
- cmd/check_cert/main.go
- replace direct usage of ExitState.LastError field with
AddError() method calls
- update annotateError() func to handle variadic list of
errors from ExitState.Errors collection
refs GH-350
> Fix various atc0005/go-nagios usage linting errors

- README.md
- note that the support is present
- mention criteria
- note problems that this validation check covers
- provide real-world use case
fixes GH-333
> README: Add new SANs list validation subsection

- README.md
- `check_cert`
- `lscert`
Since we don't yet support exporting certificates from a remote system, a brief example is given for saving a leaf certificate locally using `openssl s_client` before we evaluate it using tools from this project.
fixes GH-314
> README: Add filename flag examples

- internal/config/config.go
> Convert global config.Usage var to dedicated func

- .github/workflows/lint-and-build.yml
- .github/workflows/project-analysis.yml
- .github/workflows/push-validation.yml
- README.md
- update copyright date used by workflows
- update README to use current workflow status badges
> GitHub Actions workflows refactor follow-up

- .gitignore
- .markdownlint.yml
Fix previously missed invalid search/replace results.
> Fix project repo links

- internal/certs/certs.go
- add guard against empty certificate chain
- update doc comments to clarify behavior
> Update certs.NextToExpire to add guard, clarify

- cmd/check_cert/perfdata.go
> Remove unused/commented expires_root metric

- Makefile
- nfpm.yaml
- scripts/deb/postinstall.sh
- scripts/rpm/postinstall.sh
Use new 'packages' Makefile recipe to build DEB and RPM packages using the nFPM tool from the GoReleaser project.
fixes GH-439
See also:
- https://nfpm.goreleaser.com/
- https://github.com/goreleaser/nfpm
Thanks to the nFPM project for this awesome tool!
> Generate DEB & RPM packages using nFPM

- Makefile
- generate checksum files for packages
- update goclean recipe
- remove package checksum files
- remove links files (all & package specific)
- add links recipes
- arch/os-specific
- "wrapper" recipes to call specific ones
- add release-build recipe
- builds binaries & checksum files
- generates packages
- creates links files
- one for packages
- one for everything
refs GH-471
> Add links and release-build recipes, minor tweaks

- Makefile
- add `quick` recipe to build non-prod binaries for one-off testing purposes
- update `clean` recipe
- prune binaries generated by new `quick` recipe
- remove empty asset build paths
refs GH-471
> Add `quick` Makefile recipe

- Makefile
- split out dev binary generation to separate recipe
- add compress recipe for dev binaries
- add checksum file generation for dev binaries
- add download links files generation for dev binaries
- update `dev-build` recipe to call all of these steps in the correct order
The end result is that when generating dev builds that all dev assets can be provided for testing releases.
> Update dev build asset generation behavior

- Makefile
- add `helper-docker-builder-setup` recipe
- add new `docker-packages` recipe
- update `docker-release-build` and `docker-dev-build` recipes to use new helper to reduce duplication of recipe setup logic
> Add new recipe, refactor helper logic

- internal/certs/validation-expiration.go
Keep the focus on the leaf certificate as an expired leaf certificate has a greater impact on service availability than an expired intermediate or root certificate; browsers in particular are very forgiving of certificate chains with expired intermediate or root certificates when they are able to build alternate certificate chains, but they are NOT forgiving of expired leaf certificates.
fixes GH-281
> Give expiring/expired leaf cert highest precedence

- internal/netutils/net.go
Log at debug level for troubleshooting purposes.
> Update netutils.GetCerts to log num certs fetched

- Makefile
- packages/dev/nfpm.yaml
- packages/dev/scripts/rpm/postinstall.sh
- packages/stable/scripts/rpm/postinstall.sh
- brief notes to Makefile regarding build options
- prune nFPM config file scratch notes
- prune shell script scratch notes
> Misc cleanup tasks

- cmd/check_cert/annotations.go
This has been observed as caused by a missing IIS Site Binding on a newly upgraded Windows Server instance.
fixes GH-585
> Add advice for `connection reset by peer` error

- cmd/certsum/main_test.go
- internal/config/validate.go
- Add test to confirm invalid port flag validation
- Fix certsum port flag validation
- https://github.com/atc0005/check-cert/issues/740
> Fix certsum port flag validation

- Makefile
This adds arm64 binaries into the build process for use on ARM64 Linux machines. I've tested running `make linux` locally, and that successfully builds for all 3 linux variants now. I've added it to the `make release-build` task too, so I believe (if I've traced things correctly), then this should mean the next tagged release in GitHub would automatically have arm64 binaries published in GitHub Releases too. Thanks!
> Add Linux ARM64 binaries to build and release process

- .github/dependabot.yml
- CHANGELOG.md
- Makefile
- go.mod
8f986150dbbbc6faa5116cf3edcd26f5ec85dd03
> Sync latest changes from master branch

- README.md
Fix indentation on recent build description changes.
> Update README indentation

- cmd/check_cert/perfdata.go
- internal/certs/certs.go
New performance data metrics:
- `life_remaining_leaf`
- `life_remaining_intermediate`
New helper funcs:
- `certs.MaxLifespan`
- `certs.MaxLifespanInDays`
- `certs.LifeRemainingPercentage`
- `certs.LifeRemainingPercentageTruncated`
- GH-792
> Add certificate lifetime metrics

- README.md
Add coverage for new performance data metrics:
- `life_remaining_leaf`
- `life_remaining_intermediate`
refs GH-792
> Update README to list lifetime perfdata metrics

- cmd/check_cert/paypload.go
Replace `MultipleLeafCerts` with `DuplicateCerts`
> Update CertificateChainIssues field

- internal/certs/certs.go
List alongside cert status and expiration details.
refs GH-1037
> Add Certificate Signature Algorithm to output

- cmd/check_cert/paypload.go
- internal/certs/certs.go
Add "indicator" to Signature Algorithm listing to note whether algorithm is considered weak.
refs GH-1063
> Add indicator of weak cert signature algorithm

- internal/certs/certs.go
Emphasize that the returned value is intentionally truncated since the result may be used to calculate when a sysadmin is notified of impending expiration (and not just for display purposes).
> Note why certs.MaxLifespanInDays truncates result

- internal/certs/validation-expiration.go
Store a filtered certificate chain value as part of generating the ExpirationValidationResult value. Use that when providing a filtered certificate chain.
Rework how the validation status is determined: use the stored filtered certificate chain instead of bundling separate logic to fallback to the original cert chain if one is not provided at time of method call.
Minor cleanup of Status and StatusDetail methods.
> Refactor ExpirationValidationResult status logic

- internal/certs/certs.go
Rework the ChainPosition function and related helper functions to reduce gocognit linting scores and (hopefully) increase readability.
> Refactor cert chain position logic

- internal/certs/validation-hostname.go
Bump from minimum to maximum to reflect how severe the issue is.
refs GH-1152
> Bump priority for unhandled hostname verify fail

- README.md
- add general troubleshooting suggestions
- add coverage for explicitly setting `Content-Type` header with value of `text/plain` to work around potential issues with mailing list heuristics incorrectly detecting notifications with an embedded certificate metadata payload as binary
fixes GH-1132
> Add general and content-type troubleshooting info

- internal/certs/validation-results.go
- refactor `CertChainValidationResults.Overview`
- split out behavior into separate helper methods for reuse
- modify `CertChainValidationResults.OneLineSummary`
- drop `Overview` output (become too noisy with new checks included in summary output)
- modify `CertChainValidationResults.Report`
- add results summary block to take the place of the previously included "trailer" for the one-line summary
The goal is to provide the same overview details, but in a (hopefully) more readable format.
> Refresh CertChainValidationResults output

- internal/certs/validation-chain-order.go
- internal/certs/validation-expiration.go
- internal/certs/validation-hostname.go
- internal/certs/validation-sans.go
Rework current `IsWarningState` and `IsCriticalState` methods for current `CertChainValidationResult` implementations:
- doc comment updates
- rework `IsCriticalState` logic to explicitly handle the `ErrNoCertsFound` error
- rework `IsWarningState` method for `ChainOrderValidationResult` and `ExpirationValidationResult` types to first assert the states it is not before applying the specific WARNING state assertion it is responsible for
- refactor the `ExpirationValidationResult` `IsWarningState` and `IsCriticalState` methods to use the newly refactored `certs.HasExpiringCert` function to replace duplicate logic
> Update WARNING and CRITICAL state detection

- README.md
- plugin name
- stray word
Spotting while performing a review for other work.
> Fix misc README typos
